name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'   # Runs once daily at 3am UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats SVG
      uses: cicirello/user-statistician@v1
      with:
        colors: dark
        include-title: false
        image-file: images/userstats.svg     # Output SVG to this path
      with:
        colors: dark
        include-title: false
        image-file: images/userstats.svg
        gh_token: ${{ secrets.PULL_ALL_REPO_STATS }}

